apiVersion: v1
kind: Service
metadata:
  name: ml-flask-service
  annotations:
    # Requests an AWS Network Load Balancer (NLB)
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb" 
spec:
  selector:
    app: ml-flask # Targets the pods created by the deployment above
  ports:
    - protocol: TCP
      port: 80      # The public port for the LoadBalancer
      targetPort: 8080 # The container port (Flask)
  type: LoadBalancer # Tells AWS to provision a load balancer