apiVersion: v1
kind: Service
metadata:
  name: ml-flask-service
  annotations:
    # Requests an AWS Network Load Balancer (NLB)
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  labels:                  
    app: ml-flask          # <--- CRITICAL FIX: This label allows the ServiceMonitor to find the Service.
spec:
  selector:
    app: ml-flask          # Selects Pods with the label app: ml-flask
  ports:
    - protocol: TCP
      port: 80             # The public access port on the Load Balancer
      targetPort: 8080     # The container port (where Gunicorn is listening)
  type: LoadBalancer       # Tells Kubernetes to provision an external AWS Load Balancer